name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}/google_fotos_1:/usr/src/app/external/google_fotos_1:ro
      - ${EXTERNAL_PATH}/google_fotos_2:/usr/src/app/external/google_fotos_2:ro
      - ${EXTERNAL_PATH}/fotos_drive:/usr/src/app/external/fotos_drive:ro
      - ${EXTERNAL_PATH}/instagram_rockeira:/usr/src/app/external/instagram_rockeira:ro
      - ${EXTERNAL_PATH}/Iphone_2016:/usr/src/app/external/Iphone_2016:ro
      - ${EXTERNAL_PATH}/Iphone_2024:/usr/src/app/external/Iphone_2024:ro
      - ${EXTERNAL_PATH}/google_fotos_da_may:/usr/src/app/external/google_fotos_da_may:ro
      - ${EXTERNAL_PATH}/teteu:/usr/src/app/external/teteu:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Comment the DB_STORAGE_TYPE: 'HDD' var if your database is stored on SSDs
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache: