services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /home/home_server/Apps/lidarr/config:/config
      - /DATA/Media/Music:/music
      - /DATA/Downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /home/home_server/Apps/prowlarr/data:/config
    ports:
      - 9117:9117
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8880
      - TORRENTING_PORT=6881
    volumes:
      - /home/home_server/Apps/qbittorrent/appdata:/config
      - /DATA/Downloads:/downloads #optional
    ports:
      - 8880:8880
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped